export enum VeltrexRealtimeEventType {
  RISK_UPDATED = 'RISK_UPDATED',
  PREDICTION_UPDATED = 'PREDICTION_UPDATED',
  FIELD_REPORT_CREATED = 'FIELD_REPORT_CREATED',
  FIELD_REPORT_UPDATED = 'FIELD_REPORT_UPDATED',
  ALERT_CREATED = 'ALERT_CREATED',
  ALERT_UPDATED = 'ALERT_UPDATED',
  ALERT_ACKNOWLEDGED = 'ALERT_ACKNOWLEDGED',
  ALERT_RESOLVED = 'ALERT_RESOLVED',
  WEATHER_UPDATED = 'WEATHER_UPDATED',
  SATELLITE_UPDATED = 'SATELLITE_UPDATED',
  SYSTEM_STATUS_UPDATED = 'SYSTEM_STATUS_UPDATED',

  // Simulation Events
  SIMULATION_STARTED = 'SIMULATION_STARTED',
  SIMULATION_STEP = 'SIMULATION_STEP',
  SIMULATION_PAUSED = 'SIMULATION_PAUSED',
  SIMULATION_RESUMED = 'SIMULATION_RESUMED',
  SIMULATION_COMPLETED = 'SIMULATION_COMPLETED',
  SIMULATION_CANCELLED = 'SIMULATION_CANCELLED',
  SIMULATION_FAILED = 'SIMULATION_FAILED'
}

export type ConnectionStatus = 'LIVE' | 'CONNECTING' | 'OFFLINE' | 'RECONNECTING';

export interface VeltrexRealtimeEvent<T = any> {
  eventId: string;
  eventType: VeltrexRealtimeEventType;
  timestamp: string;
  locationId?: string;
  sequence?: number;
  source: 'SYSTEM' | 'FIELD' | 'AUTHORITY' | 'DEMO';
  data: T;
}
