import { IncidentReport } from '../types';

export const INITIAL_INCIDENTS: IncidentReport[] = [
  {
    id: 'INC-1042',
    locationName: 'Aizawl Sector 04',
    state: 'Mizoram',
    type: 'Slope Movement',
    severity: 'HIGH',
    reportedTimeAgo: '12 min ago',
    timestamp: '2026-09-04 16:35',
    status: 'Investigating',
    assignedTeam: 'Mizoram Field Unit #02',
    description: 'Tension cracks of 15cm width observed along hillside residential slope near NH-54 bypass.',
    coordinates: { lat: 23.7271, lng: 92.7176 },
    mediaUrls: ['https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=400&q=80']
  },
  {
    id: 'INC-1038',
    locationName: 'Shillong Bypass Corridor',
    state: 'Meghalaya',
    type: 'Road Blockage',
    severity: 'CRITICAL',
    reportedTimeAgo: '24 min ago',
    timestamp: '2026-09-04 16:23',
    status: 'Response Team Assigned',
    assignedTeam: 'SDRF Column #04',
    description: 'Major rockfall debris blocking both lanes of Shillong Bypass near Mawryngkneng. Heavy machinery en route.',
    coordinates: { lat: 25.5788, lng: 91.8933 },
    mediaUrls: ['https://images.unsplash.com/photo-1511497584788-8767611136f6?auto=format&fit=crop&w=400&q=80']
  },
  {
    id: 'INC-1035',
    locationName: 'Gangtok – NH10 Rangpo',
    state: 'Sikkim',
    type: 'Landslide',
    severity: 'CRITICAL',
    reportedTimeAgo: '45 min ago',
    timestamp: '2026-09-04 16:02',
    status: 'Dispatched',
    assignedTeam: 'BRO Rapid Response Column',
    description: 'Mudflow slide submerged 120m stretch of NH-10 near Rangpo bridge. Vehicles stranded.',
    coordinates: { lat: 27.3389, lng: 88.6065 },
  },
  {
    id: 'INC-1029',
    locationName: 'Kohima Phesama Bypass',
    state: 'Nagaland',
    type: 'Crack',
    severity: 'HIGH',
    reportedTimeAgo: '1 hr ago',
    timestamp: '2026-09-04 15:47',
    status: 'Investigating',
    assignedTeam: 'Nagaland DDMA Team #01',
    description: 'Subsidence crack expanding on main carriageway. Field officer logged GPS telemetry.',
    coordinates: { lat: 25.6751, lng: 94.1086 },
  },
  {
    id: 'INC-1021',
    locationName: 'Tupul Valley Section',
    state: 'Manipur',
    type: 'Rockfall',
    severity: 'HIGH',
    reportedTimeAgo: '2 hrs ago',
    timestamp: '2026-09-04 14:50',
    status: 'Resolved',
    assignedTeam: 'Railway Engineering Corps',
    description: 'Minor rockfall cleared from track cutting zone. Geotechnical monitoring ongoing.',
    coordinates: { lat: 24.817, lng: 93.9368 },
  }
];
