import { SensorDevice } from '../types';

export const INITIAL_SENSORS: SensorDevice[] = [
  {
    id: 'SM-AIZ-042',
    name: 'Soil Moisture Probe #042',
    type: 'Soil Moisture',
    locationName: 'Aizawl Sector 04',
    coordinates: { lat: 23.7271, lng: 92.7176 },
    currentValue: '91%',
    numericValue: 91,
    unit: '% VWC',
    status: 'WARNING',
    lastUpdateSec: 18,
    trend: 'Rising',
    thresholdExceeded: true,
  },
  {
    id: 'GM-AIZ-018',
    name: 'Borehole Inclinometer #018',
    type: 'Ground Movement',
    locationName: 'Aizawl Sector 04',
    coordinates: { lat: 23.7280, lng: 92.7185 },
    currentValue: '14.2 mm/h',
    numericValue: 14.2,
    unit: 'mm/h',
    status: 'WARNING',
    lastUpdateSec: 12,
    trend: 'Rising',
    thresholdExceeded: true,
  },
  {
    id: 'RG-SHL-105',
    name: 'Automatic Rain Gauge #105',
    type: 'Rain Gauge',
    locationName: 'Shillong Peak Corridor',
    coordinates: { lat: 25.5788, lng: 91.8933 },
    currentValue: '82 mm',
    numericValue: 82,
    unit: 'mm/6h',
    status: 'ONLINE',
    lastUpdateSec: 25,
    trend: 'Rising',
    thresholdExceeded: false,
  },
  {
    id: 'TS-GK-009',
    name: 'Biaxial Surface Tiltmeter #009',
    type: 'Tilt Sensor',
    locationName: 'Rangpo NH-10 Sikkim',
    coordinates: { lat: 27.3389, lng: 88.6065 },
    currentValue: '4.8°',
    numericValue: 4.8,
    unit: 'deg',
    status: 'WARNING',
    lastUpdateSec: 9,
    trend: 'Rising',
    thresholdExceeded: true,
  },
  {
    id: 'TP-KHM-033',
    name: 'Geothermal Temp Array #033',
    type: 'Temperature',
    locationName: 'Kohima Phesama',
    coordinates: { lat: 25.6751, lng: 94.1086 },
    currentValue: '19.4°C',
    numericValue: 19.4,
    unit: '°C',
    status: 'ONLINE',
    lastUpdateSec: 42,
    trend: 'Stable',
    thresholdExceeded: false,
  }
];
