export enum VeltrexRealtimeEventType {
  RISK_UPDATED = 'RISK_UPDATED',
  PREDICTION_UPDATED = 'PREDICTION_UPDATED',
  FIELD_REPORT_CREATED = 'FIELD_REPORT_CREATED',
  FIELD_REPORT_UPDATED = 'FIELD_REPORT_UPDATED',
  ALERT_CREATED = 'ALERT_CREATED',
  ALERT_UPDATED = 'ALERT_UPDATED',
  ALERT_ACKNOWLEDGED = 'ALERT_ACKNOWLEDGED',
  ALERT_RESOLVED = 'ALERT_RESOLVED',
  WEATHER_UPDATED = 'WEATHER_UPDATED',
  SATELLITE_UPDATED = 'SATELLITE_UPDATED',
  SYSTEM_STATUS_UPDATED = 'SYSTEM_STATUS_UPDATED',

  // Simulation events
  SIMULATION_STARTED = 'SIMULATION_STARTED',
  SIMULATION_STEP = 'SIMULATION_STEP',
  SIMULATION_PAUSED = 'SIMULATION_PAUSED',
  SIMULATION_RESUMED = 'SIMULATION_RESUMED',
  SIMULATION_COMPLETED = 'SIMULATION_COMPLETED',
  SIMULATION_CANCELLED = 'SIMULATION_CANCELLED',
  SIMULATION_FAILED = 'SIMULATION_FAILED'
}

export enum ClientSubscriptionEvent {
  SUBSCRIBE_LOCATION = 'subscribe:location',
  UNSUBSCRIBE_LOCATION = 'unsubscribe:location',
  SUBSCRIBE_DASHBOARD = 'subscribe:dashboard',
  UNSUBSCRIBE_DASHBOARD = 'unsubscribe:dashboard'
}
