export enum SimulationEventType {
  SIMULATION_STARTED = 'SIMULATION_STARTED',
  SIMULATION_STEP = 'SIMULATION_STEP',
  SIMULATION_PAUSED = 'SIMULATION_PAUSED',
  SIMULATION_RESUMED = 'SIMULATION_RESUMED',
  SIMULATION_COMPLETED = 'SIMULATION_COMPLETED',
  SIMULATION_CANCELLED = 'SIMULATION_CANCELLED',
  SIMULATION_FAILED = 'SIMULATION_FAILED'
}
